use gpui::*;

pub fn render() -> AnyElement {
    div()
        .flex()
        .flex_col()
        .gap(px(16.0))
        .p(px(16.0))
        .w_full()
        .child(
            div()
                .text_size(px(20.0))
                .font_weight(FontWeight::BOLD)
                .text_color(rgb(0xe0e0e0))
                .child("关于")
        )
        .child(
            div()
                .flex()
                .flex_col()
                .gap(px(24.0))
                .p(px(20.0))
                .rounded(px(16.0))
                .bg(rgb(0x1a1a1a))
                .border_1()
                .border_color(rgb(0x303030))
                .child(
                    div()
                        .flex()
                        .items_center()
                        .gap(px(16.0))
                        .child(
                            img("image/icon.png")
                                .w(px(64.0))
                                .h(px(64.0))
                        )
                        .child(
                            div()
                                .flex()
                                .flex_col()
                                .gap(px(4.0))
                                .child(
                                    div()
                                        .text_size(px(24.0))
                                        .font_weight(FontWeight::BOLD)
                                        .text_color(rgb(0xe0e0e0))
                                        .child("Xime 曦码输入法")
                                )
                                .child(
                                    div()
                                        .text_size(px(14.0))
                                        .text_color(rgb(0x808080))
                                        .child("基于 Rime 引擎的 Windows 五笔输入法")
                                )
                        )
                )
        )
        .child(
            div()
                .flex()
                .flex_col()
                .gap(px(12.0))
                .p(px(20.0))
                .rounded(px(16.0))
                .bg(rgb(0x1a1a1a))
                .border_1()
                .border_color(rgb(0x303030))
                .child(
                    div()
                        .text_size(px(16.0))
                        .font_weight(FontWeight::BOLD)
                        .text_color(rgb(0xe0e0e0))
                        .child("基本信息")
                )
                .child(render_info_row("版本".to_string(), env!("CARGO_PKG_VERSION").to_string()))
                .child(render_info_row("作者".to_string(), env!("CARGO_PKG_AUTHORS").to_string()))
                .child(render_link_row("仓库".to_string(), "https://github.com/kingzcheung/winxime".to_string()))
                .child(render_info_row("许可".to_string(), "GPL-3.0".to_string()))
        )
        .child(
            div()
                .flex()
                .flex_col()
                .gap(px(12.0))
                .p(px(20.0))
                .rounded(px(16.0))
                .bg(rgb(0x1a1a1a))
                .border_1()
                .border_color(rgb(0x303030))
                .child(
                    div()
                        .text_size(px(16.0))
                        .font_weight(FontWeight::BOLD)
                        .text_color(rgb(0xe0e0e0))
                        .child("技术栈")
                )
                .child(render_info_row("输入引擎".to_string(), "Rime (librime)".to_string()))
                .child(render_info_row("界面框架".to_string(), "Rust + TSF".to_string()))
                .child(render_info_row("UI 框架".to_string(), "GPUI".to_string()))
        )
        .into_any_element()
}

fn render_info_row(label: String, value: String) -> Div {
    div()
        .flex()
        .items_center()
        .justify_between()
        .py(px(8.0))
        .child(
            div()
                .text_size(px(14.0))
                .text_color(rgb(0x808080))
                .child(label)
        )
        .child(
            div()
                .text_size(px(14.0))
                .text_color(rgb(0xe0e0e0))
                .child(value)
        )
}

fn render_link_row(label: String, url: String) -> Div {
    div()
        .flex()
        .items_center()
        .justify_between()
        .py(px(8.0))
        .child(
            div()
                .text_size(px(14.0))
                .text_color(rgb(0x808080))
                .child(label)
        )
        .child(
            div()
                .text_size(px(14.0))
                .text_color(rgb(0x8F73E2))
                .child(url)
        )
}