name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    name: Release
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download Unsigned Installer
        uses: actions/download-artifact@v4
        with:
          name: Unsigned Installer
          path: dist
      - name: Rename and Calculate Checksum
        run: |
          mv dist/winxime-server-0.1.0-x86_64.msi dist/winxime.msi || true
          sha256sum dist/winxime.msi > dist/winxime.msi.sha256
      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          name: Xime ${{ github.ref_name }}
          draft: true
          files: |
            dist/winxime.msi
            dist/winxime.msi.sha256